# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoffeeOrderApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'NVActivityIndicatorView/AppExtension'
  pod 'JGProgressHUD'
  pod 'SDWebImageSwiftUI'
  # Pods for CoffeeOrderApp

  target 'CoffeeOrderAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoffeeOrderAppUITests' do
    # Pods for testing
  end

end
