# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DatingAPP_POC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SDWebImageSwiftUI'
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'JGProgressHUD'
  pod 'ProgressHUD'
  pod 'Firebase/Messaging'
  pod 'GeoFire'
  pod 'FBSDKLoginKit'
  pod 'AAInfographics'
  # Pods for DatingAPP_POC

  target 'DatingAPP_POCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DatingAPP_POCUITests' do
    # Pods for testing
  end

end
